[#IC-489] migrate ts-lint to eslint for io-functions-public
pagopa/io-functions-public pull request #49
Opened 2022-05-17 12:47 UTC by arcogabbo

#### List of Changes

Migrated project from tslint to eslint

#### Motivation and Context

Development purposes

#### How Has This Been Tested?

All tests run fine

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-05-18 17:07 UTC, gquadrati requested changes
Some small comments

2022-05-18 17:07 UTC, gquadrati commented on utils/healthcheck.ts
> +        // eslint-disable-next-line functional/prefer-readonly-type
duplicated
```suggestion
        // eslint-disable-next-line functional/prefer-readonly-type
```

2022-05-26 12:59 UTC, michaeldisaro approved these changes
LGTM. Just try to check the comment leave by @gquadrati .

2022-05-26 12:59 UTC, michaeldisaro commented on ValidateProfileEmail/handler.ts
> +// eslint-disable-next-line sonarjs/cognitive-complexity
@arcogabbo just try to remove it and check if linting works.

2022-05-30 12:32 UTC, merged