[IOPID-1400] Add opex dashboard for "api_backend"
pagopa/io-functions-public pull request #70
Opened 2024-01-23 09:29 UTC by lucacavallaro

#### List of Changes

Add Azure Dashboard to monitor `ValidateProfileEmail` endpoint

#### Motivation and Context

This dashboard enables us to monitor the validation e-mail endpoint, that was recently modified for the unique-email-enforcement feature

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-23 10:09 UTC, gquadrati requested changes
Add GH actions

2024-01-23 10:11 UTC, gquadrati requested changes
We need to add the TF .identity folder and setup it. Also we need to add GH actions.

2024-01-23 16:41 UTC, Krusty93 requested changes

2024-01-23 16:41 UTC, Krusty93 commented on .identity/.gitignore
> +# Local .terraform directories
I wouldn't create another .gitignore but instead I'd add tf things in the main file

2024-01-23 16:41 UTC, Krusty93 commented on .identity/00_main.tf
> +  required_version = ">=1.3.0"
`1.6.0`

2024-01-23 16:41 UTC, Krusty93 commented on .identity/00_main.tf.ci
Can be deleted

2024-01-23 16:42 UTC, Krusty93 requested changes
Most of the same comments I already wrote [here](https://github.com/pagopa/io-web-profile-backend/pull/32/files)

2024-01-25 14:37 UTC, gquadrati approved these changes

2024-01-25 14:57 UTC, merged